[0m12:27:44.286311 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7FA344AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7F80BC050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7F7F35810>]}


============================== 12:27:44.289198 | a9adbb13-aba1-4c00-bd90-b8ec0fa0ccb6 ==============================
[0m12:27:44.289198 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:27:44.289743 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init hr_analytics_dbt', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:27:44.302275 [debug] [MainThread]: Starter project path: C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\venv\Lib\site-packages\dbt\include\starter_project
[0m12:27:44.313289 [info ] [MainThread]: 
Your new dbt project "hr_analytics_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:27:44.314283 [info ] [MainThread]: Setting up your profile.
[0m12:28:19.735640 [debug] [MainThread]: Command `dbt init` succeeded at 12:28:19.735485 after 35.58 seconds
[0m12:28:19.735951 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7FB15FCE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7FB34EB10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7F9F7DAE0>]}
[0m12:28:19.736203 [debug] [MainThread]: Flushing usage events
[0m12:28:20.222690 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:33:55.598306 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018154320AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018151FFC050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018151E65810>]}


============================== 12:33:55.601076 | b90252db-a0d3-4695-8d62-cb6fe45e7a00 ==============================
[0m12:33:55.601076 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:33:55.601602 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:33:55.618092 [info ] [MainThread]: dbt version: 1.9.4
[0m12:33:55.618506 [info ] [MainThread]: python version: 3.13.1
[0m12:33:55.618791 [info ] [MainThread]: python path: C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\venv\Scripts\python.exe
[0m12:33:55.619018 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m12:33:55.680444 [info ] [MainThread]: Using profiles dir at C:\Users\joaki\.dbt
[0m12:33:55.680984 [info ] [MainThread]: Using profiles.yml file at C:\Users\joaki\.dbt\profiles.yml
[0m12:33:55.681306 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
[0m12:33:55.683600 [info ] [MainThread]: adapter type: duckdb
[0m12:33:55.683841 [info ] [MainThread]: adapter version: 1.9.3
[0m12:33:55.684079 [info ] [MainThread]: Configuration:
[0m12:33:55.684281 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m12:33:55.684472 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:33:55.684658 [info ] [MainThread]: Required dependencies:
[0m12:33:55.684856 [debug] [MainThread]: Executing "git --help"
[0m12:33:55.730536 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m12:33:55.730876 [debug] [MainThread]: STDERR: "b''"
[0m12:33:55.731125 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m12:33:55.731401 [info ] [MainThread]: Connection:
[0m12:33:55.731668 [info ] [MainThread]:   database: job_ads_pipeline
[0m12:33:55.731897 [info ] [MainThread]:   schema: staging
[0m12:33:55.732104 [info ] [MainThread]:   path: C:/Users/joaki/Desktop/HR-Analytics-Proof-of-Concept-Group-2/job_ads_pipeline.duckdb
[0m12:33:55.732294 [info ] [MainThread]:   config_options: None
[0m12:33:55.732475 [info ] [MainThread]:   extensions: None
[0m12:33:55.732653 [info ] [MainThread]:   settings: {}
[0m12:33:55.732871 [info ] [MainThread]:   external_root: .
[0m12:33:55.733055 [info ] [MainThread]:   use_credential_provider: None
[0m12:33:55.733229 [info ] [MainThread]:   attach: None
[0m12:33:55.733401 [info ] [MainThread]:   filesystems: None
[0m12:33:55.733690 [info ] [MainThread]:   remote: None
[0m12:33:55.733984 [info ] [MainThread]:   plugins: None
[0m12:33:55.734181 [info ] [MainThread]:   disable_transactions: False
[0m12:33:55.734542 [info ] [MainThread]: Registered adapter: duckdb=1.9.3
[0m12:33:55.908846 [debug] [MainThread]: Acquiring new duckdb connection 'debug'
[0m12:33:55.957116 [debug] [MainThread]: Using duckdb connection "debug"
[0m12:33:55.957386 [debug] [MainThread]: On debug: select 1 as id
[0m12:33:55.957548 [debug] [MainThread]: Opening a new connection, currently in state init
[0m12:33:56.004703 [debug] [MainThread]: DuckDB adapter: Error running SQL: select 1 as id
[0m12:33:56.005006 [debug] [MainThread]: DuckDB adapter: Rolling back transaction.
[0m12:33:56.005215 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m12:33:56.005656 [info ] [MainThread]: [31m2 checks failed:[0m
[0m12:33:56.005983 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml> not found

[0m12:33:56.006282 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Runtime Error
  IO Error: File is already open in 
  C:\Users\joaki\Downloads\duckdb_cli-windows-amd64\duckdb.exe (PID 8264)

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m12:33:56.007109 [debug] [MainThread]: Command `dbt debug` failed at 12:33:56.007029 after 0.52 seconds
[0m12:33:56.007305 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m12:33:56.007488 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018156AB5350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000181567B7410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001815674FCE0>]}
[0m12:33:56.007714 [debug] [MainThread]: Flushing usage events
[0m12:33:57.688097 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:47:04.660831 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E64B160AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E648E3C050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E648CB5810>]}


============================== 10:47:04.670041 | 976b9da1-b19d-4346-836c-646d1505f95e ==============================
[0m10:47:04.670041 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:47:04.670628 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:47:04.671047 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:47:04.672035 [debug] [MainThread]: Command `dbt run` failed at 10:47:04.671948 after 0.11 seconds
[0m10:47:04.672269 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E64BF7E650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E64BEBF1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E64C0E0490>]}
[0m10:47:04.672475 [debug] [MainThread]: Flushing usage events
[0m10:47:05.143876 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:47:27.481113 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D09B84AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D0784C050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D076B5810>]}


============================== 10:47:27.484831 | d793981d-2279-4499-b014-d75290194460 ==============================
[0m10:47:27.484831 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:47:27.485445 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:47:27.485932 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:47:27.486876 [debug] [MainThread]: Command `dbt run` failed at 10:47:27.486782 after 0.10 seconds
[0m10:47:27.487137 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D0A99E650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D0A8DF1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020D0AB00490>]}
[0m10:47:27.487400 [debug] [MainThread]: Flushing usage events
[0m10:47:27.941394 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:20:49.701062 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AB19214AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AB16EEC050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AB16D55810>]}


============================== 11:20:49.703780 | d6d43ba1-8ab9-46a6-964c-1be0e55b7173 ==============================
[0m11:20:49.703780 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:20:49.704192 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m11:20:49.704508 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:20:49.705199 [debug] [MainThread]: Command `dbt run` failed at 11:20:49.705124 after 0.14 seconds
[0m11:20:49.705406 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AB1A02E650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AB19F6F1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AB1A190490>]}
[0m11:20:49.705603 [debug] [MainThread]: Flushing usage events
[0m11:20:50.147997 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:35:17.417984 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD307B4AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD2E4BC050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD2E335810>]}


============================== 18:35:17.420953 | 85b3c943-edfb-4af4-b88d-c1f961dab270 ==============================
[0m18:35:17.420953 [info ] [MainThread]: Running with dbt=1.9.4
[0m18:35:17.421457 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select fct_job_ads', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:35:17.421875 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:35:17.422581 [debug] [MainThread]: Command `dbt run` failed at 18:35:17.422504 after 0.14 seconds
[0m18:35:17.422784 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD315CE650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD3150F1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD31730490>]}
[0m18:35:17.422981 [debug] [MainThread]: Flushing usage events
[0m18:35:26.042538 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:46:34.513814 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FADEEE4AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FADCBCC050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FADCA45810>]}


============================== 12:46:34.517602 | 3aa07b11-61e0-416f-8f9c-82f43a3199f3 ==============================
[0m12:46:34.517602 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:46:34.518442 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt build', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:46:34.518859 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:46:34.519547 [debug] [MainThread]: Command `dbt build` failed at 12:46:34.519469 after 0.13 seconds
[0m12:46:34.519761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FADFD02650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FADFC471D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FADFE5C490>]}
[0m12:46:34.519959 [debug] [MainThread]: Flushing usage events
[0m12:46:35.025194 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:30:54.448116 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025826C64AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002582493C050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000258247A5810>]}


============================== 12:30:54.451365 | 1a5decae-e4be-4b47-8f8e-77bb4b7623a7 ==============================
[0m12:30:54.451365 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:30:54.451967 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:30:54.452388 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:30:54.453076 [debug] [MainThread]: Command `dbt run` failed at 12:30:54.452997 after 0.13 seconds
[0m12:30:54.453289 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025827A82650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000258279C31D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025827BD8490>]}
[0m12:30:54.453491 [debug] [MainThread]: Flushing usage events
[0m12:30:54.934093 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:26:48.537684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029BD45F4AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029BD22CC050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029BD2135810>]}


============================== 17:26:48.540457 | e9b0c64a-2711-4706-aa29-24c0ac3df0f0 ==============================
[0m17:26:48.540457 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:26:48.540953 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt build', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:26:48.541360 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:26:48.542044 [debug] [MainThread]: Command `dbt build` failed at 17:26:48.541970 after 0.11 seconds
[0m17:26:48.542250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029BD5412650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029BD53531D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029BD556C490>]}
[0m17:26:48.542444 [debug] [MainThread]: Flushing usage events
[0m17:26:49.030809 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:28:00.200149 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000183746D4AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000183723AC050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018372215810>]}


============================== 17:28:00.203012 | b18b6c34-d88e-444f-896d-72e4f5055154 ==============================
[0m17:28:00.203012 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:28:00.203545 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt build', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:28:00.204010 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:28:00.204721 [debug] [MainThread]: Command `dbt build` failed at 17:28:00.204644 after 0.10 seconds
[0m17:28:00.204961 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000183754F2650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000183754371D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001837564C490>]}
[0m17:28:00.205185 [debug] [MainThread]: Flushing usage events
[0m17:28:00.687174 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:59:51.516018 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002325E284AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002325BF5C050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002325BDC5810>]}


============================== 13:59:51.518960 | cfa2ae3b-99ea-4acb-9475-bd75ecdc4f07 ==============================
[0m13:59:51.518960 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:59:51.519540 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\joaki\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build --full-refresh', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:59:51.519974 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\joaki\Desktop\HR-Analytics-Proof-of-Concept-Group-2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:59:51.520725 [debug] [MainThread]: Command `dbt build` failed at 13:59:51.520642 after 0.15 seconds
[0m13:59:51.520960 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002325F0A2650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002325EFE71D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002325F1FC490>]}
[0m13:59:51.521186 [debug] [MainThread]: Flushing usage events
[0m13:59:51.995487 [debug] [MainThread]: An error was encountered while trying to flush usage events
